### ISSUE TITLE
Can this be used to get consensus annotations for an ortholog/orthogroup?

### ISSUE THREAD

**Issue by jolespin** [PedroMTQ/mantis#37] opened 2021-12-14 01:28 UTC
Let's say we have 3 proteins that get clustered together in an ortholog analysis. They all have very similar but slightly different annotations. Can this tool pick a consensus annotation? If so, what is the best way to do this on the program?

**Comment by PedroMTQ** [comment] 2021-12-15 09:02
Hello @jolespin,
Mantis checks for the consensus of annotations per protein. So, in your scenario this is not something that could be done natively by Mantis.
I did create another [tool](https://github.com/PedroMTQ/UniFunc) that could help with this, it is used by Mantis to do some a similarity analysis of the annotations. In your case, I believe you would only have to assess the similarity of the annotations in your cluster. Based on the similarity score you could then perhaps choose the annotation with the highest pairwise similarity within your cluster? This way you could have a representative annotation for that cluster.
This shouldn't be too hard to implement.
Anyway, please let me know if you have any questions or require further help.

Regards,
Pedro

**Comment by jolespin** [comment] 2021-12-15 15:01
Thanks for the suggestion. You're doing some really interesting work with applying NLP to biological data! This might be a bit tricky to use in my case because it wants the protein sequences as input strings. Some of the orthogroups have 100 or so proteins and some of the proteins are pretty long for commandline. This would also take a very long time to run these commands pairwise. Is there a functionality that takes in a fasta file like FastANI but with proteins?

**Comment by PedroMTQ** [comment] 2021-12-15 15:13
Hello @jolespin 
Thank you for the feedback!
I'm a bit confused with what you mean by " it wants the protein sequences as input strings". The input for UniFunc is actually a pair of strings such as "this protein degrades glucose".
Regarding runtime, yes, it might take a bit longer for larger clusters, but this would probably be a matter of testing it a bit and perhaps doing some pre-processing beforehand?

Regarding the command-line, I could also implement some sort of workflow for this, e.g.:
you could input a tsv with:
clusterX protein1 annotation
clusterX protein2 annotation
clusterY protein 3 annotation
etc

and an output with:
clusterX - most representative function
clusterY - most representative function

Anyway, just brainstorming here, but it should be feasible (and do let me know if this is something you'd like to see implemented).

Regards,
Pedro

**Comment by jolespin** [comment] 2021-12-15 15:34
Oh!! Ok, I misunderstood the input strings. I thought those strings were the actual protein sequences and not the annotations. This makes more sense now.

Yes, the suggestion you made about the tab input would be really useful. One more feature that could be useful would be to put lower weight on strings that had specific phrases such as "hypothetical protein", "predicted protein", "low quality", etc. When I hard coded a very crude version of this, that's one of the edge cases I had to deal with. There were orthogroups that had like 6 proteins, half were some version of hypothetical/predicted and the others were very obviously a classified protein all within the same orthogroup. In that case, it would be better to take the annotated hit to a known protein over a hypothetical. 

One more thing, in the output could you also include the similarity score? 

One last edge case, removing the accession and species substrings would be really good too. For hits the NR, it includes "accession name [species]" format. Sometimes the species name has a bracket in it so parsing is a little tricky

**Comment by PedroMTQ** [comment] 2021-12-15 16:06
Hello @jolespin,

Yes, UniFunc already gives lower weight to those sort of annotations. But maybe you could give me a list so that I could cross-check with my implementation? ATM I only included things I routinely saw when I was analyzing functional annotations but I might have missed a few.
Yes, sure the similarity score can be included.

Actually, it would be useful to have a sample input with enough variability so I could implement the workflow (including the accession and species strings).

Regards,
Pedro

**Comment by jolespin** [comment] 2021-12-15 21:44
Apologies for the delay, I had to clean up the formatting a bit. 

Here's a subset of my data: 
[gene_orthogroup_annotation.tsv.gz](https://github.com/PedroMTQ/mantis/files/7722835/gene_orthogroup_annotation.tsv.gz)

Format:
`[GeneID]<tab>[OrthogroupID]<tab>[Annotation]`

It contains: 
* 461619 genes
* 46823 orthogroups
* 102018 missing annotations 

Not sure what your thoughts were for output but off the top of my head, the most useful outputs would be the following files: 
* `[Orthogroup/Cluster]<tab>[Score of annotation]<tab>[Annotation]` (Not sure if score would be. Maybe summed weight of annotation over all weights? You would have a much better idea of this than me. I'll need to read the paper in more detail)
* `[Orthogroup_1]<tab>[Protein_A]<tab>[Protein_B]<tab>[Similarity]` (A non-redundant version to keep file sizes smaller)

The former would be the main output and the latter would make it easier to throw into `NetworkX` for network analysis or convert into a distance matrix for clustering. The latter is extra only if its easy to implement.

**Comment by PedroMTQ** [comment] 2021-12-16 09:00
Hello @jolespin 

I will add this to my to-do list. Give me a few days to implement it and I'll get back to you.

Regards,
Pedro

**Comment by jolespin** [comment] 2021-12-16 18:36
Please let me know if you need a smaller list of proteins or anything else.

**Comment by PedroMTQ** [comment] 2021-12-17 14:41
Hello @jolespin 

I'm implementing this atm. Just some questions:
1- How do you want to deal with missing annotations? Ignore them completely ? This might give a false perception of the score of the most representative score if most clusters are lacking an annotation.
2- How do you want to deal with hypothethical proteins with some sort of ID, e.g.,hypothetical protein FRACYDRAFT_204728?  These IDs can cause a lot of disparity in some clusters (e.g., OG0000032)
3- How do you want to handle clusters where the more than one representative annotation exists (non-similar)?

Regards,
Pedro

**Comment by jolespin** [comment] 2021-12-17 15:46
Thanks for looking into this.

>1- How do you want to deal with missing annotations? Ignore them completely ? This might give a false perception of the score of the most representative score if most clusters are lacking an annotation.

This is tricky and you bring up an excellent point. I think including them in the weights but not in the annotation. For example, there are 3 proteins in a cluster. Two of them point to protein A and one of them has no annotation. I think the most appropriate way to not inflate the score would be to treat the unannotated as a hypothetical and include it in the weight. Maybe an option to not include the unannotated would be good to but with a note saying this could artificially inflate the scores and not having this as the default?

>2- How do you want to deal with hypothethical proteins with some sort of ID, e.g.,hypothetical protein FRACYDRAFT_204728? These IDs can cause a lot of disparity in some clusters (e.g., OG0000032)

What I've been doing is anything that has hypothetical, predicted, etc. I just force as "hypothetical protein" and remove all identifiers. In this vein, it might be good to have an option that says prioritize non-hypotheticals or something so people can either have SOME annotation or if they were interested in diving deeper into what the hypotheticals could be they could retain the hypothetical annotation. 

>3- How do you want to handle clusters where the more than one representative annotation exists (non-similar)?

For this, I would concat the strings with something like a |. The tricky thing is what to do with the annotation score...at first glance, I would say split down the middle but I can imagine cases where there are 5 proteins, one is a random, 2 are referring to protein A, and 2 are referring to protein B. Merging the annotations for protein A and B would make sense but you wouldn't be able to split the score in half... maybe a vector of scores in this case? Maybe subtracting one protein from the total score and then splitting the remainder down the middle?

**Comment by PedroMTQ** [comment] 2021-12-20 09:47
Hello @jolespin 

I've more or less implemented it. Feel free to check it out at:
https://github.com/PedroMTQ/UniFunc/tree/main/Workflows/Representative_function

You should test it and check if there's anything that needs to changed in the methodology. I also haven't benchmarked the methodology nor thoroughly checked the results, but I leave that to you as you probably have more expertise on that domain.
One important note: if you do apply this code to similar results, then you need to provide the input tsv sorted by orthogroups (as you did in your sample file). I'm using a generator to reduce memory footprint, and it only works if the orthogroups are sorted (I can make the implementation more general if you prefer).

If nothing urgent comes up I will close this comment, but feel free to continue the discussion in the UniFunc repo.
Anyway, hope it helps.

Regards,
Pedro

**Comment by jolespin** [comment] 2021-12-20 22:39
I'm having trouble running the script and putting UniFunc in my path: 

```
(unifunc_env) -bash-4.2$ conda list
# packages in environment at /usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/unifunc_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
brotlipy                  0.7.0           py39h3811e60_1003    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8        py39hf3d152e_1    conda-forge
cffi                      1.15.0           py39h4bc2ebd_0    conda-forge
charset-normalizer        2.0.9              pyhd8ed1ab_0    conda-forge
click                     8.0.3            py39hf3d152e_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cryptography              36.0.0           py39h9ce1e76_0
idna                      3.1                pyhd3deb0d_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nltk                      3.6.5              pyhd8ed1ab_0    conda-forge
openssl                   3.0.0                h7f98852_2    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39hf3d152e_4    conda-forge
python                    3.9.9           h543edf9_0_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
regex                     2021.11.10       py39h3811e60_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_1    conda-forge
setuptools                59.7.0           py39hf3d152e_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
(unifunc_env) -bash-4.2$ ls
Images  __init__.py  LICENSE  __main__.py  __pycache__  README.md  Resources  source.py  unifunc_env.yml  Workflows
(unifunc_env) -bash-4.2$ python Workflows/Representative_function/get_cluster_representative_function.py -h
Traceback (most recent call last):
  File "/local/ifs2_devel/ANNOTATION/jespinoz/Packages/UniFunc/Workflows/Representative_function/get_cluster_representative_function.py", line 32, in <module>
    from source import UniFunc
ModuleNotFoundError: No module named 'source'
```

**Comment by PedroMTQ** [comment] 2021-12-21 08:14
Hello @jolespin ,

I added the argparser to make it easier to run. 
Now it should be fine when you try to run it using:
`python UniFunc/Workflows/Representative_function/Cluster_Representative_Function.py -h`

Regards,
Pedro

**Comment by jolespin** [comment] 2021-12-25 17:05
Is it possible to add these scripts and UniFunc into my conda bin? I haven't seen this type of directory structure where there isn't a unifunc script I could symlink. Is it pip installable?

**Comment by PedroMTQ** [comment] 2021-12-30 11:50
Hello @jolespin 
Sorry for the delay.
ATM UniFunc is not installable with pip, I'm working on making it conda installable but I can't make it a priority on my to-do list (maybe I'll manage in the next few weeks).
In the meantime, you can call it by just using `python path/to/.py -args`

Regards,
Pedro

**Closed as completed** 2022-01-05 10:56 UTC
Labels: question

**Comment by jolespin** [comment] 2022-01-27 17:42
![image](https://user-images.githubusercontent.com/9061708/151413748-570f5038-6ff4-40fd-a11b-4fc8fcb24f35.png)

Not sure if you would prefer I mention this here or on UniFunc's repo but I noticed that the `rep_func_cluster.tsv` includes multiple hits for some of the groups (e.g., orthogroups). 

What happens in this type of edge case? Could it be faulty input or should the highest score be taken each time.

**Comment by PedroMTQ** [comment] 2022-01-28 07:11
Hello @jolespin 
Well, this is actually intended behavior, seeing that I implemented it so that we check for similar functions and we output functional clusters that are above a certain threshold.
In those cases they are highly similar and since the cluster could be represented by either, I decided to just output both.

However, what I could do is go one step further and check which tokens in your function string actually holds the most weight and output the function string that has, on average, the most significant tokens.

Anyhow, let me know what you think.

Regards,
Pedro

**Comment by PedroMTQ** [comment] 2022-01-28 08:25
Implemented in added v1.4.2

**Comment by jolespin** [comment] 2022-01-31 23:46
I've updated to v1.4.2 but now get an error: 

```python
(unifunc_env) -bash-4.2$ unifunc cluster_function -i orf-orthogroup-annotation.no_header.tsv -o unifunc_output/ -kh
Creating functional clusters for orf-orthogroup-annotation.no_header.tsv
Traceback (most recent call last):
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/unifunc_env/bin/unifunc", line 10, in <module>
    sys.exit(main())
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/unifunc_env/lib/python3.9/site-packages/unifunc/__main__.py", line 84, in main
    argv_cluster_representative_function()
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/unifunc_env/lib/python3.9/site-packages/unifunc/__main__.py", line 65, in argv_cluster_representative_function
    Cluster_Representative_Function(input_path=input_path,
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/unifunc_env/lib/python3.9/site-packages/Workflows/Representative_function/Cluster_Representative_Function.py", line 50, in __init__
    self.get_representative_function()
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/unifunc_env/lib/python3.9/site-packages/Workflows/Representative_function/Cluster_Representative_Function.py", line 307, in get_representative_function
    annotations=self.get_most_significant_function(annotations)
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/unifunc_env/lib/python3.9/site-packages/Workflows/Representative_function/Cluster_Representative_Function.py", line 282, in get_most_significant_function
    vector_list = self.process_string_nlp(tokens_lists)
AttributeError: 'Cluster_Representative_Function' object has no attribute 'process_string_nlp'


(unifunc_env) -bash-4.2$ conda list | grep "unifunc"
# packages in environment at /usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/unifunc_env:
unifunc                   1.4.2              pyhd8ed1ab_0    conda-forge
```

**Comment by PedroMTQ** [comment] 2022-02-01 07:13
Hello,

Sorry about that, I forgot to add some code from my local testing.

Anyhow, v1.4.3 should have it, please wait just for a few hours for conda-forge CI to add the new packaged version 

Regards,
Pedro

**Comment by jolespin** [comment] 2022-02-01 20:46
Looks like it's up now: 
https://anaconda.org/conda-forge/unifunc

All looks good to go! I just ran it on my dataset. Thank you.

**Comment by PedroMTQ** [comment] 2022-02-01 21:11
Great. No worries
